export interface Destination {
  name: string;
  state: string;
  subZone: string;
  desc: string;
  activity: string;
  duration: string;
  transport: string;
  accommodation: string;
  budget: number;
  emoji: string;
  mapLink: string;
  imageLink: string;
  videoLink: string;
  submittedBy?: string;
}

export const statesData: Record<string, { coords: [[number,number],[number,number]]; color: string; subZones: string[] }> = {
  'Andhra Pradesh': { coords: [[13.2, 79.5], [17.5, 84.5]], color: '#FAC496', subZones: ['Vizag','Araku','Rayalaseema','North Godavari','Konaseema','Chitoor','South Rayalaseema','Srikakulam','North Coastal Zone','Vizianagaram','Ananthapur District Zone'] },
  'Telangana': { coords: [[15.5, 78.0], [19.0, 81.5]], color: '#32B8C6', subZones: ['Hyderabad','Warangal','Khammam','Mahbubnagar'] },
  'Rajasthan': { coords: [[23.0, 72.0], [28.5, 78.5]], color: '#f39c12', subZones: ['Dhundhar','Thar','Aaravali','Mewar','Shikawati'] },
  'Goa': { coords: [[14.5, 73.5], [15.5, 74.0]], color: '#2ecc71', subZones: ['North Goa','South Goa','Central Zone'] }
};

export const destinations: Destination[] = [
  {name:"Bheemunipatnam Beach",state:"Andhra Pradesh",subZone:"Vizag",desc:"Has a beautiful coast",activity:"nature",duration:"short",transport:"Bus/Local Transport",accommodation:"midrange",budget:500,emoji:"🏖️",mapLink:"https://maps.app.goo.gl/gVnZafAzR1DRoGrj8",imageLink:"https://timesofindia.indiatimes.com/travel/destinations/explore-the-legends-of-bheemili-beach-and-its-dutch-connect/articleshow/69891298.cms",videoLink:"https://www.youtube.com/watch?v=yUdR3SY0Rnc"},
  {name:"Araku Valley",state:"Andhra Pradesh",subZone:"Araku",desc:"Scenic hill station with tribal culture",activity:"cultural",duration:"short",transport:"train",accommodation:"budget",budget:2000,emoji:"🏔️",mapLink:"https://maps.app.goo.gl/7tbz8BcASRRSrBFG9",imageLink:"https://www.thrillophilia.com/destinations/araku-valley-guides",videoLink:"https://www.youtube.com/watch?v=SjLqT4cNvDc"},
  {name:"Uppada Beach and Mangrove Villages",state:"Andhra Pradesh",subZone:"Vizag",desc:"Scenic beaches and mangroves",activity:"cultural",duration:"short",transport:"train/Bus",accommodation:"budget",budget:1000,emoji:"🏖️",mapLink:"https://maps.app.goo.gl/MRJGFUU2hiyyR2wk6",imageLink:"https://www.makemytrip.com/tripideas/attractions/uppada-beach",videoLink:"https://www.youtube.com/watch?v=PtR4JfPg31A"},
  {name:"Bojjana Konda",state:"Andhra Pradesh",subZone:"Vizag",desc:"Buddhist historical monuments",activity:"cultural",duration:"short",transport:"Bus/Local",accommodation:"midrange",budget:500,emoji:"🏔️",mapLink:"https://maps.app.goo.gl/W2yVmxgm6szKJmEx7",imageLink:"https://www.instagram.com/p/CZTKkfXp3c1/",videoLink:"https://www.youtube.com/watch?v=a9yQ4tCOpdo"},
  {name:"Thotlakonda Buddhist Complex",state:"Andhra Pradesh",subZone:"Vizag",desc:"Buddhist sites",activity:"cultural",duration:"short",transport:"Bus/Local",accommodation:"midrange",budget:900,emoji:"🏔️",mapLink:"https://maps.app.goo.gl/b8fzwz4ccu7zpzQF9",imageLink:"https://www.shutterstock.com/image-photo/thotlakonda-buddhist-complex",videoLink:"https://www.youtube.com/watch?v=JQ3OgoEXo3c"},
  {name:"Ananthagiri Coffee Plantations",state:"Andhra Pradesh",subZone:"Araku",desc:"Coffee Plantations",activity:"cultural",duration:"short",transport:"Local",accommodation:"budget",budget:800,emoji:"🌿",mapLink:"https://maps.app.goo.gl/1wGF61iwWn6qXMSNA",imageLink:"https://www.alamy.com/stock-photo/araku-valley-coffee-plantation.html",videoLink:"https://www.youtube.com/shorts/g7I2LntKHOM"},
  {name:"Padmapuram Botanical Garden",state:"Andhra Pradesh",subZone:"Araku",desc:"Botanical Garden",activity:"cultural",duration:"short",transport:"Local",accommodation:"budget",budget:1000,emoji:"🌳",mapLink:"https://maps.app.goo.gl/nMbuzdWpLeNVG5bz6",imageLink:"https://www.thehindu.com/news/cities/Visakhapatnam/padmapuram-botanical-gardens-in-araku-valley",videoLink:"https://www.youtube.com/watch?v=F6fOWo833-M"},
  {name:"Gandikota Canyon",state:"Andhra Pradesh",subZone:"Rayalaseema",desc:"India's Grand Canyon - spectacular gorges",activity:"adventure",duration:"short",transport:"Local",accommodation:"midrange",budget:1000,emoji:"⛰️",mapLink:"https://maps.app.goo.gl/MZDfnzFJsGN7FvJ97",imageLink:"https://naturewalkers.in/trek/gandikota-camping-belum-caves",videoLink:"https://www.youtube.com/watch?v=683c_aWrtRk"},
  {name:"Maredumalli Forest Trek",state:"Andhra Pradesh",subZone:"Vizag",desc:"Tropical forest with trekking",activity:"adventure",duration:"short",transport:"Local",accommodation:"midrange",budget:800,emoji:"🌴",mapLink:"https://maps.app.goo.gl/5j1857zqctCfrCpk8",imageLink:"https://www.tripadvisor.in/Attraction_Review-g1155908-d14042455",videoLink:"https://www.facebook.com/livyoungphotography1/videos/831314614200787"},
  {name:"Papikondalu",state:"Andhra Pradesh",subZone:"North Godavari",desc:"Scenic Beauty with Boating",activity:"adventure",duration:"short",transport:"flight",accommodation:"midrange",budget:1200,emoji:"⛰️",mapLink:"https://maps.app.goo.gl/t6mrc7xJYE3iMYwo7",imageLink:"https://papikondalu.net.in/",videoLink:"https://www.youtube.com/watch?v=De-Mp57Jee4"},
  {name:"Bobbili War Memorial",state:"Andhra Pradesh",subZone:"Vizianagaram",desc:"Historic War Memorial",activity:"photography",duration:"short",transport:"Bus/Local",accommodation:"midrange",budget:500,emoji:"🪖",mapLink:"https://maps.app.goo.gl/FCPrKzz5zLdHAF7v9",imageLink:"https://www.justdial.com/Vizianagaram/War-Memorial-Pillar-Bobbili",videoLink:"https://www.instagram.com/reel/DFMDOyzz-ph/"},
  {name:"Penukonda Fort",state:"Andhra Pradesh",subZone:"South Rayalaseema",desc:"Vizinagara Fort",activity:"adventure",duration:"short",transport:"Local",accommodation:"midrange",budget:1200,emoji:"🏦",mapLink:"https://maps.app.goo.gl/Q83WM1CLUEPv12nJ6",imageLink:"https://www.incredibleindia.gov.in/en/andhra-pradesh/anantapur/penukonda-fort",videoLink:"https://www.youtube.com/watch?v=DtIDZ6D76zo"},
  {name:"Chorao Island",state:"Goa",subZone:"North Goa",desc:"Tropical beaches with vibrant culture",activity:"adventure",duration:"short",transport:"flight",accommodation:"midrange",budget:1000,emoji:"🏝️",mapLink:"https://maps.app.goo.gl/F3oxxoX8ifUVchY68",imageLink:"https://seawatersports.com/places/goa/chorao-island-in-goa",videoLink:"https://www.youtube.com/watch?v=1bJMoSTs4rA"},
  {name:"Corjuem Fort",state:"Goa",subZone:"North Goa",desc:"Historic Portuguese Fort",activity:"adventure",duration:"short",transport:"flight",accommodation:"midrange",budget:1000,emoji:"🏦",mapLink:"https://maps.app.goo.gl/qtgfdvZhsx8i31V69",imageLink:"https://www.incredibleindia.gov.in/en/trips/trip-listing/goa-unveiled",videoLink:"https://www.youtube.com/watch?v=JWewJqZ9Gro"},
  {name:"Usgalimal Rock Carvings",state:"Goa",subZone:"South Goa",desc:"Ancient Petroglyphs",activity:"cultural",duration:"short",transport:"flight",accommodation:"midrange",budget:1200,emoji:"🪨",mapLink:"https://maps.app.goo.gl/T8m4N7bgdUmpSPo16",imageLink:"https://timesofindia.indiatimes.com/travel/destinations/unforgettable-goa-with-usgalimal-rock-carvings",videoLink:"https://www.youtube.com/watch?v=WFDPnD3em4k"},
  {name:"Cotigao Wildlife Sanctuary",state:"Goa",subZone:"South Goa",desc:"Wildlife Sanctuary",activity:"adventure",duration:"short",transport:"flight",accommodation:"midrange",budget:700,emoji:"🫎",mapLink:"https://maps.app.goo.gl/GWBxpCE8Pxxa8pbb8",imageLink:"https://www.thegoavilla.com/goa/destination/cotigao-wildlife-sanctuary.html",videoLink:"https://www.youtube.com/watch?v=U4oaqFheGYI"},
  {name:"Mandovi River Cruises",state:"Goa",subZone:"Central Zone",desc:"Scenic river cruise with cultural performances",activity:"adventure",duration:"short",transport:"flight",accommodation:"midrange",budget:1200,emoji:"🛳️",mapLink:"https://maps.app.goo.gl/5WnqRGC9HLvinsqR8",imageLink:"https://www.thrillophilia.com/tours/mandovi-boat-cruise-with-dinner",videoLink:"https://www.youtube.com/watch?v=31Tp9vac1lU"},
  {name:"Qutb Shahi Tombs",state:"Telangana",subZone:"Hyderabad",desc:"Magnificent Qutb Shahi dynasty monuments",activity:"cultural",duration:"short",transport:"flight",accommodation:"midrange",budget:1200,emoji:"🪦",mapLink:"https://maps.app.goo.gl/8XhjEniLAdsD2L3r8",imageLink:"https://www.telegraphindia.com/my-kolkata/places/eighty-qutb-shahi-dynasty-structures",videoLink:"https://www.youtube.com/watch?v=zJ-zSc8UN94"},
  {name:"Eturnagaran Lakes & Jungle",state:"Telangana",subZone:"Warangal",desc:"Adventure zone with lakes and jungle",activity:"adventure",duration:"short",transport:"local",accommodation:"budget",budget:800,emoji:"🍁",mapLink:"https://maps.app.goo.gl/c4o7y9euHwy2yhj86",imageLink:"https://bogatha.feriadoresorts.com/travel-inspiration-attractions-at-bogatha-waterfalls/",videoLink:"https://www.youtube.com/watch?v=HeP8IPU4LcA"},
  {name:"Mallela Theertham Waterfalls",state:"Telangana",subZone:"Khammam",desc:"Hidden waterfalls in dense forest",activity:"adventure",duration:"short",transport:"Bus/Local",accommodation:"midrange",budget:1200,emoji:"🤽",mapLink:"https://maps.app.goo.gl/fRw8iyP1ZMWnEA99A",imageLink:"https://www.tripadvisor.in/Attraction_Review-g12389577-d7199477",videoLink:"https://www.youtube.com/watch?v=3-dJtkQRbLA"},
  {name:"Nallamalla Forest",state:"Telangana",subZone:"Mahbubnagar",desc:"Pristine forest reserve with tribal culture",activity:"adventure",duration:"short",transport:"Bus/Local",accommodation:"midrange",budget:1200,emoji:"🍃",mapLink:"https://maps.app.goo.gl/Rz8MNM8wRvjkhCum7",imageLink:"https://www.tripadvisor.in/Attraction_Review-g12389577-Nallamalla-Forest",videoLink:"https://www.youtube.com/watch?v=3-dJtkQRbLA"},
  {name:"Jaipur's Hidden Treks",state:"Rajasthan",subZone:"Dhundhar",desc:"Desert Forts and hidden trekking trails",activity:"adventure",duration:"medium",transport:"Train/Bus",accommodation:"midrange",budget:1200,emoji:"🏜️",mapLink:"https://maps.app.goo.gl/hTa8yDPJMaagmc259",imageLink:"https://www.thrillophilia.com/destinations/jaipur",videoLink:"https://www.youtube.com/watch?v=zrCX3H9WYHA"},
  {name:"Khuri Sand Dunes",state:"Rajasthan",subZone:"Thar",desc:"Authentic desert experience with camel safaris",activity:"adventure",duration:"medium",transport:"Local",accommodation:"midrange",budget:1200,emoji:"🐫",mapLink:"https://maps.app.goo.gl/XnGKvM5pi3tqa16a9",imageLink:"https://www.tourism.rajasthan.gov.in/khuri.html",videoLink:"https://www.youtube.com/watch?v=2qZEMPM8M4o"},
  {name:"Kumbhalgarh Fort",state:"Rajasthan",subZone:"Aaravali",desc:"Massive fort with longest wall in the world",activity:"adventure",duration:"medium",transport:"Local",accommodation:"midrange",budget:1200,emoji:"🌵",mapLink:"https://maps.app.goo.gl/3SBBdUXb5W38HhuE8",imageLink:"https://www.tourism.rajasthan.gov.in/rajsamand.html",videoLink:"https://www.youtube.com/watch?v=DBg24dG48WQ"},
];
